In [1]:
import pandas as pd
import numpy as np
import pygeohash as pgh
import matplotlib.pyplot as plt
import geohash2
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
train_df = pd.read_csv("../data/raw/train.csv")
test_df = pd.read_csv("../data/raw/test.csv")

print(train_df.shape)
print(test_df.shape)

train_df.head()

(77299, 11)
(41778, 10)

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,NaN,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy

In [3]:
train_df.columns

Index(['Index', 'geohash', 'day', 'timestamp', 'demand', 'RoadType',
       'NumberofLanes', 'LargeVehicles', 'Landmarks', 'Temperature',
       'Weather'],
      dtype='str')

In [4]:
for col in train_df.columns:
    # print(col)
    # print(train_df[col].unique()[:5])
    print(col,": ",train_df[col].dtype)

Index :  int64
geohash :  str
day :  int64
timestamp :  str
demand :  float64
RoadType :  str
NumberofLanes :  int64
LargeVehicles :  str
Landmarks :  str
Temperature :  float64
Weather :  str

# Data cleaning

In [5]:
def convert_string_columns_to_lowercase(df: pd.DataFrame) -> pd.DataFrame:
    """
    Convert all string/object columns to lowercase.

    Parameters
    ----------
    df : pd.DataFrame
        Input dataframe

    Returns
    -------
    pd.DataFrame
        Dataframe with lowercase string values
    """
    df = df.copy()

    str_cols = df.select_dtypes(include=["object"]).columns

    for col in str_cols:
        df[col] = df[col].astype(str).str.lower()

    return df


def fill_categorical_missing_values(
    df: pd.DataFrame,
    categorical_cols: list
) -> pd.DataFrame:
    """
    Replace NaN and 'nan' strings in categorical columns
    with the most frequent value (mode).

    Parameters
    ----------
    df : pd.DataFrame
        Input dataframe
    categorical_cols : list
        List of categorical columns

    Returns
    -------
    pd.DataFrame
        Updated dataframe
    """
    df = df.copy()

    for col in categorical_cols:

        # Convert string 'nan' back to actual NaN
        df[col] = df[col].replace("nan", np.nan)

        # Most frequent value
        mode_value = df[col].mode()[0]

        # Fill missing values
        df[col] = df[col].fillna(mode_value)

    return df


def fill_temperature_missing_values(df: pd.DataFrame) -> pd.DataFrame:
    """
    Replace missing Temperature values with mean temperature.

    Parameters
    ----------
    df : pd.DataFrame

    Returns
    -------
    pd.DataFrame
    """
    df = df.copy()

    mean_temp = df["Temperature"].mean()

    df["Temperature"] = df["Temperature"].fillna(mean_temp)

    return df

In [6]:

def clean_dataset(org_df: pd.DataFrame) -> pd.DataFrame:
    """
    Complete data cleaning pipeline.

    Steps:
    1. Convert all strings to lowercase
    2. Fill missing RoadType with mode
    3. Fill missing Weather with mode
    4. Fill missing Temperature with mean

    Parameters
    ----------
    org_df : pd.DataFrame

    Returns
    -------
    pd.DataFrame
    """
    df = org_df.copy()
    try:
        df = convert_string_columns_to_lowercase(df)

        df = fill_categorical_missing_values(
            df,
            categorical_cols=["RoadType", "Weather"]
        )

        df = fill_temperature_missing_values(df)

        return df

    except Exception as e:
        print(f"Error occurred while cleaning dataset: {e}")
        return org_df

# Feature engineering

In [7]:
def add_lat_lon(df: pd.DataFrame) -> pd.DataFrame:
    """
    Decode geohash into latitude and longitude.
    """
    df = df.copy()

    decoded = df["geohash"].apply(geohash2.decode)

    df["lat"] = decoded.apply(lambda x: x[0])
    df["lon"] = decoded.apply(lambda x: x[1])

    return df


def add_hour_feature(df: pd.DataFrame) -> pd.DataFrame:
    """
    Extract hour from timestamp column.

    Example:
    '13:45' -> 13
    """
    df = df.copy()

    df["hour"] = (
        df["timestamp"]
        .astype(str)
        .str.split(":")
        .str[0]
        .astype(int)
    )

    return df


def add_geo_hour_feature(df: pd.DataFrame) -> pd.DataFrame:
    """
    Create geohash-hour interaction feature.
    """
    df = df.copy()

    df["geo_hour"] = (
        df["geohash"].astype(str)
        + "_"
        + df["hour"].astype(str)
    )

    return df


def get_period(hour: int) -> str:
    """
    Map hour to time period.
    """

    if hour < 5:
        return "night"

    elif hour < 12:
        return "morning"

    elif hour < 17:
        return "afternoon"

    elif hour < 21:
        return "evening"

    else:
        return "late_night"


def add_period_feature(df: pd.DataFrame) -> pd.DataFrame:
    """
    Create period feature from hour.
    """
    df = df.copy()

    df["period"] = df["hour"].apply(get_period)

    return df


def add_geo_period_feature(df: pd.DataFrame) -> pd.DataFrame:
    """
    Create geohash-period interaction feature.
    """
    df = df.copy()

    df["geo_period"] = (
        df["geohash"].astype(str)
        + "_"
        + df["period"].astype(str)
    )

    return df


def add_roadtype_period_feature(df: pd.DataFrame) -> pd.DataFrame:
    """
    Create RoadType-period interaction feature.
    """
    df = df.copy()

    df["roadtype_period"] = (
        df["RoadType"].astype(str)
        + "_"
        + df["period"].astype(str)
    )

    return df

def add_cyclical_hour_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add cyclical encoding for hour using sine and cosine.
    Assumes hour is in [0, 23].
    """
    df = df.copy()

    df["sin_hour"] = np.sin(2 * np.pi * df["hour"] / 24)
    df["cos_hour"] = np.cos(2 * np.pi * df["hour"] / 24)

    return df

def add_cyclical_day_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add cyclical encoding for day using sine and cosine.
    Assumes day is in [0, 6].
    """
    df = df.copy()

    df["sin_day"] = np.sin(2 * np.pi * df["day"] / 7)
    df["cos_day"] = np.cos(2 * np.pi * df["day"] / 7)

    return df

def add_squared_temperature(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add squared temperature feature.
    """
    df = df.copy()

    df["temperature_sq"] = df["Temperature"] ** 2 - df["Temperature"]

    return df

def add_hour_squared(df):
    df = df.copy()
    df["hour_sq"] = df["hour"] ** 2
    return df

def add_rush_hour_flag(df):
    df = df.copy()

    df["is_morning_peak"] = (
        df["hour"].between(7, 9)
    ).astype(int)

    df["is_evening_peak"] = (
        df["hour"].between(17, 20)
    ).astype(int)

    return df

def add_spatial_interaction(df):
    df = df.copy()

    lat = df["lat"].astype(float)
    lon = df["lon"].astype(float)

    df["lat_lon_interaction"] = lat * lon

    return df

def add_temp_bucket(df):
    df = df.copy()

    df["temp_bucket"] = pd.cut(
        df["Temperature"],
        bins=[-100, 15, 25, 35, 100],
        labels=["cold", "mild", "warm", "hot"]
    )

    return df

def add_weather_temp(df):
    df = df.copy()

    df["weather_temp"] = (
        df["Weather"].astype(str)
        + "_"
        + pd.cut(
            df["Temperature"],
            bins=[-100,15,25,35,100],
            labels=["cold","mild","warm","hot"]
        ).astype(str)
    )

    return df

def add_geo_weather(df):
    df = df.copy()

    df["geo_weather"] = (
        df["geohash"].astype(str)
        + "_"
        + df["Weather"].astype(str)
    )

    return df

def add_geo_road(df):
    df = df.copy()

    df["geo_road"] = (
        df["geohash"].astype(str)
        + "_"
        + df["RoadType"].astype(str)
    )

    return df

def add_geo_temp_bucket(df):
    df = df.copy()

    bucket = pd.cut(
        df["Temperature"],
        bins=[-100,15,25,35,100],
        labels=["cold","mild","warm","hot"]
    )

    df["geo_temp"] = (
        df["geohash"].astype(str)
        + "_"
        + bucket.astype(str)
    )

    return df

In [8]:
def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Complete feature engineering pipeline.

    Features created:
    - lat
    - lon
    - hour
    - geo_hour
    - period
    - geo_period
    - roadtype_period
    - sin_hour
    - cos_hour
    - temperature_sq
    - hour_sq
    - is_morning_peak
    - is_evening_peak
    - lat_lon_interaction
    - temp_bucket
    - weather_temp
    - geo_weather
    - geo_road
    - geo_temp
    """
    df = add_lat_lon(df)

    df = add_hour_feature(df)

    df = add_geo_hour_feature(df)

    df = add_period_feature(df)

    df = add_geo_period_feature(df)

    df = add_roadtype_period_feature(df)

    df = add_cyclical_hour_features(df)

    df = add_squared_temperature(df)

    df = add_hour_squared(df)

    df = add_rush_hour_flag(df)

    df = add_spatial_interaction(df)

    df = add_temp_bucket(df)

    df = add_weather_temp(df)

    df = add_geo_weather(df)

    df = add_geo_road(df)

    df = add_geo_temp_bucket(df)

    return df

In [9]:
train_df = clean_dataset(train_df)

/tmp/ipykernel_15764/3791486193.py:17: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  str_cols = df.select_dtypes(include=["object"]).columns

In [10]:
train_df = engineer_features(train_df)

In [11]:
train_df.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,...,temperature_sq,hour_sq,is_morning_peak,is_evening_peak,lat_lon_interaction,temp_bucket,weather_temp,geo_weather,geo_road,geo_temp
0,0,qp02z1,48,0:0,0.048804,residential,1,not allowed,no,16.405354,...,252.730296,0,0,0,-497.036,mild,sunny_mild,qp02z1_sunny,qp02z1_residential,qp02z1_mild
1,1,qp02zt,48,0:0,0.118507,residential,3,allowed,yes,31.104565,...,936.389375,0,0,0,-495.222,warm,sunny_warm,qp02zt_sunny,qp02zt_residential,qp02zt_warm
2,2,qp08bj,48,0:0,0.027132,residential,1,not allowed,no,25.919267,...,645.889151,0,0,0,-495.222,warm,sunny_warm,qp08bj_sunny,qp08bj_residential,qp08bj_warm
3,3,qp08gt,48,0:0,0.003272,residential,1,not allowed,no,16.405354,...,252.730296,0,0,0,-496.314,mild,rainy_mild,qp08gt_rainy,qp08gt_residential,qp08gt_mild
4,4,qp02zq,48,0:0,0.010819,residential,1,not allowed,no,10.803667,...,105.915563,0,0,0,-495.222,cold,rainy_cold,qp02zq_rainy,qp02zq_residential,qp02zq_cold

In [12]:
for col in train_df.columns:
    # print(col)
    # print(train_df[col].unique()[:5])
    print(col,": ",train_df[col].dtype)

Index :  int64
geohash :  str
day :  int64
timestamp :  str
demand :  float64
RoadType :  str
NumberofLanes :  int64
LargeVehicles :  str
Landmarks :  str
Temperature :  float64
Weather :  str
lat :  str
lon :  str
hour :  int64
geo_hour :  str
period :  str
geo_period :  str
roadtype_period :  str
sin_hour :  float64
cos_hour :  float64
temperature_sq :  float64
hour_sq :  int64
is_morning_peak :  int64
is_evening_peak :  int64
lat_lon_interaction :  float64
temp_bucket :  category
weather_temp :  str
geo_weather :  str
geo_road :  str
geo_temp :  str

# Training

In [13]:
import os
import joblib
import numpy as np
import pandas as pd

from tqdm.auto import tqdm

from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor

In [14]:
TARGET = "demand"

DROP_COLS = [
    "Index",
    "timestamp",
    TARGET
]

FEATURE_COLS = [
    c for c in train_df.columns
    if c not in DROP_COLS
]

CAT_COLS = [
    "geohash",
    "RoadType",
    "LargeVehicles",
    "Landmarks",
    "Weather",
    "geo_hour",
    "period",
    "geo_period",
    "roadtype_period",

    # New categorical features
    "temp_bucket",
    "weather_temp",
    "geo_weather",
    "geo_road",
    "geo_temp",
]

In [15]:
kf = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

cat_scores = []

best_cat_model = None
best_cat_rmse = np.inf

In [16]:
for fold, (train_idx, valid_idx) in enumerate(kf.split(train_df), 1):

    print(f"\nFold {fold}")

    train_fold = train_df.iloc[train_idx].copy()
    valid_fold = train_df.iloc[valid_idx].copy()

    X_train = train_fold[FEATURE_COLS]
    y_train = train_fold[TARGET]

    X_valid = valid_fold[FEATURE_COLS]
    y_valid = valid_fold[TARGET]

    model = CatBoostRegressor(
        iterations=5000,
        learning_rate=0.015,
        depth=10,
        loss_function="RMSE",
        eval_metric="RMSE",
        random_seed=42,
        early_stopping_rounds=300,
        verbose=100
    )

    model.fit(
        X_train,
        y_train,
        cat_features=CAT_COLS,
        eval_set=(X_valid, y_valid),
        use_best_model=True
    )

    preds = model.predict(X_valid)

    rmse = np.sqrt(
        mean_squared_error(
            y_valid,
            preds
        )
    )

    r2 = r2_score(
        y_valid,
        preds
    )

    cat_scores.append(rmse)

    print(f"Fold RMSE: {rmse:.6f}")
    print(f"Fold R²  : {r2:.6f}")

    if rmse < best_cat_rmse:
        best_cat_rmse = rmse
        best_cat_model = model

Fold 1
0:	learn: 0.1404026	test: 0.1404558	best: 0.1404558 (0)	total: 113ms	remaining: 9m 26s
100:	learn: 0.0558338	test: 0.0542709	best: 0.0542709 (100)	total: 4.87s	remaining: 3m 56s
200:	learn: 0.0412413	test: 0.0404579	best: 0.0404579 (200)	total: 9.85s	remaining: 3m 55s
300:	learn: 0.0372673	test: 0.0371151	best: 0.0371151 (300)	total: 15.6s	remaining: 4m 3s
400:	learn: 0.0354381	test: 0.0357010	best: 0.0357010 (400)	total: 21.8s	remaining: 4m 9s
500:	learn: 0.0341927	test: 0.0348565	best: 0.0348565 (500)	total: 27.3s	remaining: 4m 4s
600:	learn: 0.0330948	test: 0.0341515	best: 0.0341515 (600)	total: 32.7s	remaining: 3m 59s
700:	learn: 0.0322887	test: 0.0336870	best: 0.0336870 (700)	total: 37.9s	remaining: 3m 52s
800:	learn: 0.0315197	test: 0.0332374	best: 0.0332374 (800)	total: 43.3s	remaining: 3m 47s
900:	learn: 0.0308608	test: 0.0329035	best: 0.0329035 (900)	total: 48.7s	remaining: 3m 41s
1000:	learn: 0.0302832	test: 0.0326310	best: 0.0326310 (1000)	total: 54.1s	remaining: 3m 35s
1100:	learn: 0.0297892	test: 0.0324114	best: 0.0324114 (1100)	total: 59.6s	remaining: 3m 31s
1200:	learn: 0.0293467	test: 0.0322223	best: 0.0322223 (1200)	total: 1m 5s	remaining: 3m 26s
1300:	learn: 0.0289284	test: 0.0320616	best: 0.0320616 (1300)	total: 1m 10s	remaining: 3m 21s
1400:	learn: 0.0285764	test: 0.0319360	best: 0.0319358 (1399)	total: 1m 16s	remaining: 3m 17s
1500:	learn: 0.0282344	test: 0.0318143	best: 0.0318143 (1500)	total: 1m 22s	remaining: 3m 13s
1600:	learn: 0.0279066	test: 0.0317371	best: 0.0317371 (1600)	total: 1m 28s	remaining: 3m 8s
1700:	learn: 0.0275794	test: 0.0316626	best: 0.0316626 (1700)	total: 1m 34s	remaining: 3m 3s
1800:	learn: 0.0272840	test: 0.0315989	best: 0.0315989 (1800)	total: 1m 40s	remaining: 2m 59s
1900:	learn: 0.0270003	test: 0.0315368	best: 0.0315368 (1900)	total: 1m 46s	remaining: 2m 54s
2000:	learn: 0.0267252	test: 0.0314774	best: 0.0314774 (1999)	total: 1m 53s	remaining: 2m 50s
2100:	learn: 0.0264571	test: 0.0314323	best: 0.0314323 (2100)	total: 1m 59s	remaining: 2m 45s
2200:	learn: 0.0261920	test: 0.0313943	best: 0.0313931 (2197)	total: 2m 6s	remaining: 2m 40s
2300:	learn: 0.0259466	test: 0.0313417	best: 0.0313417 (2300)	total: 2m 12s	remaining: 2m 35s
2400:	learn: 0.0257164	test: 0.0313042	best: 0.0313041 (2399)	total: 2m 18s	remaining: 2m 30s
2500:	learn: 0.0254992	test: 0.0312725	best: 0.0312709 (2493)	total: 2m 25s	remaining: 2m 24s
2600:	learn: 0.0252606	test: 0.0312339	best: 0.0312320 (2589)	total: 2m 31s	remaining: 2m 19s
2700:	learn: 0.0250465	test: 0.0312015	best: 0.0312015 (2700)	total: 2m 37s	remaining: 2m 13s
2800:	learn: 0.0248286	test: 0.0311681	best: 0.0311674 (2798)	total: 2m 43s	remaining: 2m 8s
2900:	learn: 0.0246229	test: 0.0311447	best: 0.0311447 (2900)	total: 2m 49s	remaining: 2m 2s
3000:	learn: 0.0244357	test: 0.0311212	best: 0.0311209 (2996)	total: 2m 55s	remaining: 1m 57s
3100:	learn: 0.0242416	test: 0.0311022	best: 0.0311022 (3100)	total: 3m 2s	remaining: 1m 51s
3200:	learn: 0.0240582	test: 0.0310801	best: 0.0310796 (3198)	total: 3m 8s	remaining: 1m 45s
3300:	learn: 0.0238399	test: 0.0310602	best: 0.0310597 (3297)	total: 3m 14s	remaining: 1m 40s
3400:	learn: 0.0236474	test: 0.0310401	best: 0.0310385 (3389)	total: 3m 20s	remaining: 1m 34s
3500:	learn: 0.0234602	test: 0.0310186	best: 0.0310186 (3500)	total: 3m 26s	remaining: 1m 28s
3600:	learn: 0.0232739	test: 0.0310021	best: 0.0310021 (3600)	total: 3m 32s	remaining: 1m 22s
3700:	learn: 0.0230935	test: 0.0309809	best: 0.0309809 (3700)	total: 3m 39s	remaining: 1m 16s
3800:	learn: 0.0229135	test: 0.0309634	best: 0.0309634 (3800)	total: 3m 45s	remaining: 1m 11s
3900:	learn: 0.0227350	test: 0.0309524	best: 0.0309522 (3898)	total: 3m 51s	remaining: 1m 5s
4000:	learn: 0.0225502	test: 0.0309436	best: 0.0309426 (3962)	total: 3m 58s	remaining: 59.4s
4100:	learn: 0.0223982	test: 0.0309369	best: 0.0309348 (4046)	total: 4m 4s	remaining: 53.6s
4200:	learn: 0.0222507	test: 0.0309239	best: 0.0309236 (4197)	total: 4m 10s	remaining: 47.7s
4300:	learn: 0.0220900	test: 0.0309206	best: 0.0309198 (4297)	total: 4m 16s	remaining: 41.7s
4400:	learn: 0.0219449	test: 0.0309095	best: 0.0309093 (4390)	total: 4m 22s	remaining: 35.8s
4500:	learn: 0.0217959	test: 0.0309031	best: 0.0309028 (4498)	total: 4m 28s	remaining: 29.8s
4600:	learn: 0.0216433	test: 0.0308985	best: 0.0308957 (4586)	total: 4m 34s	remaining: 23.8s
4700:	learn: 0.0215045	test: 0.0308900	best: 0.0308898 (4682)	total: 4m 40s	remaining: 17.9s
4800:	learn: 0.0213495	test: 0.0308778	best: 0.0308778 (4800)	total: 4m 46s	remaining: 11.9s
4900:	learn: 0.0212048	test: 0.0308747	best: 0.0308747 (4900)	total: 4m 53s	remaining: 5.92s
4999:	learn: 0.0210631	test: 0.0308670	best: 0.0308653 (4976)	total: 4m 58s	remaining: 0us

bestTest = 0.03086534878
bestIteration = 4976

Shrink model to first 4977 iterations.
Fold RMSE: 0.030865
Fold R²  : 0.952918

Fold 2
0:	learn: 0.1396966	test: 0.1432065	best: 0.1432065 (0)	total: 39.3ms	remaining: 3m 16s
100:	learn: 0.0562366	test: 0.0579030	best: 0.0579030 (100)	total: 4.17s	remaining: 3m 22s
200:	learn: 0.0414193	test: 0.0426265	best: 0.0426265 (200)	total: 8.7s	remaining: 3m 27s
300:	learn: 0.0374465	test: 0.0387560	best: 0.0387560 (300)	total: 13.7s	remaining: 3m 33s
400:	learn: 0.0355280	test: 0.0369987	best: 0.0369987 (400)	total: 19.3s	remaining: 3m 40s
500:	learn: 0.0342318	test: 0.0359929	best: 0.0359929 (500)	total: 24.4s	remaining: 3m 39s
600:	learn: 0.0332571	test: 0.0352819	best: 0.0352819 (600)	total: 29.5s	remaining: 3m 35s
700:	learn: 0.0323495	test: 0.0346958	best: 0.0346958 (700)	total: 34.4s	remaining: 3m 31s
800:	learn: 0.0316451	test: 0.0342393	best: 0.0342393 (800)	total: 39.6s	remaining: 3m 27s
900:	learn: 0.0310935	test: 0.0339104	best: 0.0339104 (900)	total: 44.6s	remaining: 3m 22s
1000:	learn: 0.0306039	test: 0.0336141	best: 0.0336141 (1000)	total: 49.7s	remaining: 3m 18s
1100:	learn: 0.0300937	test: 0.0333529	best: 0.0333529 (1100)	total: 54.8s	remaining: 3m 14s
1200:	learn: 0.0296133	test: 0.0331196	best: 0.0331196 (1200)	total: 1m	remaining: 3m 9s
1300:	learn: 0.0291676	test: 0.0329048	best: 0.0329048 (1300)	total: 1m 5s	remaining: 3m 6s
1400:	learn: 0.0287492	test: 0.0326903	best: 0.0326903 (1400)	total: 1m 11s	remaining: 3m 2s
1500:	learn: 0.0283436	test: 0.0325236	best: 0.0325236 (1500)	total: 1m 16s	remaining: 2m 58s
1600:	learn: 0.0279540	test: 0.0323947	best: 0.0323947 (1600)	total: 1m 21s	remaining: 2m 54s
1700:	learn: 0.0275827	test: 0.0323007	best: 0.0322996 (1699)	total: 1m 27s	remaining: 2m 49s
1800:	learn: 0.0272869	test: 0.0322176	best: 0.0322167 (1799)	total: 1m 32s	remaining: 2m 44s
1900:	learn: 0.0269975	test: 0.0321118	best: 0.0321118 (1900)	total: 1m 37s	remaining: 2m 39s
2000:	learn: 0.0267147	test: 0.0320350	best: 0.0320350 (2000)	total: 1m 43s	remaining: 2m 34s
2100:	learn: 0.0264616	test: 0.0319760	best: 0.0319760 (2100)	total: 1m 48s	remaining: 2m 30s
2200:	learn: 0.0262208	test: 0.0319205	best: 0.0319202 (2199)	total: 1m 54s	remaining: 2m 25s
2300:	learn: 0.0259774	test: 0.0318640	best: 0.0318640 (2300)	total: 2m	remaining: 2m 20s
2400:	learn: 0.0257308	test: 0.0318082	best: 0.0318082 (2400)	total: 2m 5s	remaining: 2m 15s
2500:	learn: 0.0255182	test: 0.0317680	best: 0.0317680 (2500)	total: 2m 11s	remaining: 2m 11s
2600:	learn: 0.0252977	test: 0.0317151	best: 0.0317150 (2599)	total: 2m 16s	remaining: 2m 6s
2700:	learn: 0.0250636	test: 0.0316687	best: 0.0316687 (2700)	total: 2m 22s	remaining: 2m 1s
2800:	learn: 0.0248555	test: 0.0316258	best: 0.0316258 (2800)	total: 2m 27s	remaining: 1m 56s
2900:	learn: 0.0246487	test: 0.0315835	best: 0.0315835 (2900)	total: 2m 33s	remaining: 1m 51s
3000:	learn: 0.0244374	test: 0.0315565	best: 0.0315560 (2998)	total: 2m 39s	remaining: 1m 46s
3100:	learn: 0.0242578	test: 0.0315292	best: 0.0315292 (3100)	total: 2m 44s	remaining: 1m 41s
3200:	learn: 0.0240498	test: 0.0314916	best: 0.0314915 (3199)	total: 2m 50s	remaining: 1m 36s
3300:	learn: 0.0238496	test: 0.0314457	best: 0.0314456 (3299)	total: 2m 56s	remaining: 1m 30s
3400:	learn: 0.0236640	test: 0.0314258	best: 0.0314250 (3385)	total: 3m 1s	remaining: 1m 25s
3500:	learn: 0.0234933	test: 0.0314088	best: 0.0314088 (3497)	total: 3m 7s	remaining: 1m 20s
3600:	learn: 0.0233063	test: 0.0313915	best: 0.0313915 (3600)	total: 3m 13s	remaining: 1m 15s
3700:	learn: 0.0231372	test: 0.0313713	best: 0.0313704 (3699)	total: 3m 19s	remaining: 1m 9s
3800:	learn: 0.0229538	test: 0.0313474	best: 0.0313471 (3799)	total: 3m 25s	remaining: 1m 4s
3900:	learn: 0.0227924	test: 0.0313242	best: 0.0313237 (3895)	total: 3m 31s	remaining: 59.4s
4000:	learn: 0.0226226	test: 0.0313028	best: 0.0313028 (4000)	total: 3m 36s	remaining: 54.2s
4100:	learn: 0.0224763	test: 0.0312835	best: 0.0312835 (4100)	total: 3m 42s	remaining: 48.9s
4200:	learn: 0.0223269	test: 0.0312659	best: 0.0312657 (4199)	total: 3m 48s	remaining: 43.5s
4300:	learn: 0.0221750	test: 0.0312544	best: 0.0312537 (4276)	total: 3m 54s	remaining: 38.1s
4400:	learn: 0.0220305	test: 0.0312416	best: 0.0312409 (4398)	total: 4m	remaining: 32.7s
4500:	learn: 0.0218882	test: 0.0312266	best: 0.0312257 (4489)	total: 4m 6s	remaining: 27.3s
4600:	learn: 0.0217585	test: 0.0312138	best: 0.0312127 (4589)	total: 4m 11s	remaining: 21.9s
4700:	learn: 0.0216177	test: 0.0311997	best: 0.0311997 (4700)	total: 4m 17s	remaining: 16.4s
4800:	learn: 0.0214825	test: 0.0311915	best: 0.0311912 (4793)	total: 4m 23s	remaining: 10.9s
4900:	learn: 0.0213471	test: 0.0311811	best: 0.0311810 (4897)	total: 4m 28s	remaining: 5.43s
4999:	learn: 0.0212068	test: 0.0311703	best: 0.0311702 (4996)	total: 4m 35s	remaining: 0us

bestTest = 0.03117019823
bestIteration = 4996

Shrink model to first 4997 iterations.
Fold RMSE: 0.031170
Fold R²  : 0.953792

Fold 3
0:	learn: 0.1404600	test: 0.1402191	best: 0.1402191 (0)	total: 59ms	remaining: 4m 55s
100:	learn: 0.0559541	test: 0.0555084	best: 0.0555084 (100)	total: 4.42s	remaining: 3m 34s
200:	learn: 0.0415143	test: 0.0409912	best: 0.0409912 (200)	total: 9.28s	remaining: 3m 41s
300:	learn: 0.0377297	test: 0.0374302	best: 0.0374302 (300)	total: 14.5s	remaining: 3m 45s
400:	learn: 0.0358583	test: 0.0357969	best: 0.0357969 (400)	total: 20.5s	remaining: 3m 54s
500:	learn: 0.0343932	test: 0.0347504	best: 0.0347504 (500)	total: 26.3s	remaining: 3m 56s
600:	learn: 0.0332225	test: 0.0339829	best: 0.0339829 (600)	total: 32s	remaining: 3m 54s
700:	learn: 0.0322918	test: 0.0334633	best: 0.0334633 (700)	total: 37.7s	remaining: 3m 51s
800:	learn: 0.0314324	test: 0.0329771	best: 0.0329771 (800)	total: 43.3s	remaining: 3m 47s
900:	learn: 0.0307492	test: 0.0325991	best: 0.0325991 (900)	total: 49s	remaining: 3m 42s
1000:	learn: 0.0301851	test: 0.0323188	best: 0.0323188 (1000)	total: 54.8s	remaining: 3m 38s
1100:	learn: 0.0296830	test: 0.0320885	best: 0.0320885 (1100)	total: 1m	remaining: 3m 34s
1200:	learn: 0.0292415	test: 0.0319220	best: 0.0319220 (1200)	total: 1m 6s	remaining: 3m 30s
1300:	learn: 0.0288240	test: 0.0317750	best: 0.0317750 (1300)	total: 1m 12s	remaining: 3m 26s
1400:	learn: 0.0284396	test: 0.0316487	best: 0.0316487 (1400)	total: 1m 18s	remaining: 3m 21s
1500:	learn: 0.0280903	test: 0.0315528	best: 0.0315528 (1500)	total: 1m 24s	remaining: 3m 16s
1600:	learn: 0.0277520	test: 0.0314606	best: 0.0314605 (1599)	total: 1m 29s	remaining: 3m 10s
1700:	learn: 0.0274398	test: 0.0313838	best: 0.0313838 (1700)	total: 1m 36s	remaining: 3m 7s
1800:	learn: 0.0271282	test: 0.0313077	best: 0.0313076 (1799)	total: 1m 42s	remaining: 3m 2s
1900:	learn: 0.0268655	test: 0.0312524	best: 0.0312524 (1900)	total: 1m 48s	remaining: 2m 57s
2000:	learn: 0.0265976	test: 0.0311781	best: 0.0311779 (1999)	total: 1m 55s	remaining: 2m 52s
2100:	learn: 0.0263442	test: 0.0311098	best: 0.0311098 (2100)	total: 2m 1s	remaining: 2m 47s
2200:	learn: 0.0260973	test: 0.0310555	best: 0.0310555 (2200)	total: 2m 7s	remaining: 2m 41s
2300:	learn: 0.0258512	test: 0.0309866	best: 0.0309866 (2300)	total: 2m 13s	remaining: 2m 36s
2400:	learn: 0.0256125	test: 0.0309542	best: 0.0309542 (2400)	total: 2m 19s	remaining: 2m 30s
2500:	learn: 0.0253789	test: 0.0309154	best: 0.0309154 (2500)	total: 2m 25s	remaining: 2m 25s
2600:	learn: 0.0251693	test: 0.0308789	best: 0.0308777 (2599)	total: 2m 31s	remaining: 2m 19s
2700:	learn: 0.0249610	test: 0.0308423	best: 0.0308423 (2700)	total: 2m 37s	remaining: 2m 14s
2800:	learn: 0.0247646	test: 0.0308073	best: 0.0308073 (2800)	total: 2m 43s	remaining: 2m 8s
2900:	learn: 0.0245719	test: 0.0307880	best: 0.0307867 (2896)	total: 2m 50s	remaining: 2m 3s
3000:	learn: 0.0243897	test: 0.0307634	best: 0.0307634 (3000)	total: 2m 56s	remaining: 1m 57s
3100:	learn: 0.0241905	test: 0.0307450	best: 0.0307433 (3082)	total: 3m 2s	remaining: 1m 51s
3200:	learn: 0.0240017	test: 0.0307187	best: 0.0307179 (3199)	total: 3m 8s	remaining: 1m 46s
3300:	learn: 0.0238073	test: 0.0307028	best: 0.0307028 (3300)	total: 3m 14s	remaining: 1m 40s
3400:	learn: 0.0236234	test: 0.0306818	best: 0.0306815 (3393)	total: 3m 21s	remaining: 1m 34s
3500:	learn: 0.0234488	test: 0.0306719	best: 0.0306712 (3486)	total: 3m 27s	remaining: 1m 28s
3600:	learn: 0.0232862	test: 0.0306519	best: 0.0306519 (3600)	total: 3m 33s	remaining: 1m 22s
3700:	learn: 0.0231188	test: 0.0306314	best: 0.0306310 (3699)	total: 3m 39s	remaining: 1m 17s
3800:	learn: 0.0229455	test: 0.0306112	best: 0.0306112 (3800)	total: 3m 46s	remaining: 1m 11s
3900:	learn: 0.0227815	test: 0.0305927	best: 0.0305927 (3900)	total: 3m 52s	remaining: 1m 5s
4000:	learn: 0.0226333	test: 0.0305801	best: 0.0305801 (4000)	total: 3m 58s	remaining: 59.7s
4100:	learn: 0.0224772	test: 0.0305708	best: 0.0305707 (4099)	total: 4m 5s	remaining: 53.7s
4200:	learn: 0.0223283	test: 0.0305594	best: 0.0305589 (4197)	total: 4m 11s	remaining: 47.8s
4300:	learn: 0.0221839	test: 0.0305431	best: 0.0305428 (4299)	total: 4m 17s	remaining: 41.8s
4400:	learn: 0.0220415	test: 0.0305284	best: 0.0305284 (4397)	total: 4m 23s	remaining: 35.9s
4500:	learn: 0.0219035	test: 0.0305214	best: 0.0305202 (4488)	total: 4m 29s	remaining: 29.9s
4600:	learn: 0.0217682	test: 0.0305170	best: 0.0305163 (4571)	total: 4m 36s	remaining: 23.9s
4700:	learn: 0.0216239	test: 0.0305073	best: 0.0305073 (4700)	total: 4m 42s	remaining: 18s
4800:	learn: 0.0214828	test: 0.0304970	best: 0.0304970 (4800)	total: 4m 48s	remaining: 12s
4900:	learn: 0.0213368	test: 0.0304860	best: 0.0304860 (4900)	total: 4m 55s	remaining: 5.96s
4999:	learn: 0.0212214	test: 0.0304782	best: 0.0304775 (4987)	total: 5m 1s	remaining: 0us

bestTest = 0.03047752192
bestIteration = 4987

Shrink model to first 4988 iterations.
Fold RMSE: 0.030478
Fold R²  : 0.953923

Fold 4
0:	learn: 0.1412951	test: 0.1366980	best: 0.1366980 (0)	total: 55.4ms	remaining: 4m 36s
100:	learn: 0.0562302	test: 0.0544956	best: 0.0544956 (100)	total: 4.7s	remaining: 3m 48s
200:	learn: 0.0416159	test: 0.0414458	best: 0.0414458 (200)	total: 9.53s	remaining: 3m 47s
300:	learn: 0.0375516	test: 0.0379755	best: 0.0379755 (300)	total: 14.9s	remaining: 3m 52s
400:	learn: 0.0357132	test: 0.0364196	best: 0.0364196 (400)	total: 20.6s	remaining: 3m 56s
500:	learn: 0.0343079	test: 0.0354447	best: 0.0354447 (500)	total: 25.9s	remaining: 3m 52s
600:	learn: 0.0332486	test: 0.0347674	best: 0.0347674 (600)	total: 31.3s	remaining: 3m 49s
700:	learn: 0.0322551	test: 0.0341332	best: 0.0341332 (700)	total: 36.8s	remaining: 3m 45s
800:	learn: 0.0314330	test: 0.0336399	best: 0.0336399 (800)	total: 42.4s	remaining: 3m 42s
900:	learn: 0.0307916	test: 0.0333115	best: 0.0333115 (900)	total: 48s	remaining: 3m 38s
1000:	learn: 0.0302190	test: 0.0330450	best: 0.0330450 (1000)	total: 54.1s	remaining: 3m 36s
1100:	learn: 0.0297269	test: 0.0328306	best: 0.0328306 (1100)	total: 59.8s	remaining: 3m 31s
1200:	learn: 0.0292631	test: 0.0326764	best: 0.0326764 (1200)	total: 1m 5s	remaining: 3m 27s
1300:	learn: 0.0288272	test: 0.0325311	best: 0.0325303 (1299)	total: 1m 11s	remaining: 3m 22s
1400:	learn: 0.0284130	test: 0.0324072	best: 0.0324072 (1400)	total: 1m 17s	remaining: 3m 18s
1500:	learn: 0.0280552	test: 0.0322845	best: 0.0322845 (1500)	total: 1m 23s	remaining: 3m 14s
1600:	learn: 0.0277544	test: 0.0322013	best: 0.0322013 (1600)	total: 1m 29s	remaining: 3m 9s
1700:	learn: 0.0274327	test: 0.0320774	best: 0.0320774 (1700)	total: 1m 35s	remaining: 3m 4s
1800:	learn: 0.0271123	test: 0.0319785	best: 0.0319785 (1800)	total: 1m 41s	remaining: 2m 59s
1900:	learn: 0.0268146	test: 0.0318962	best: 0.0318962 (1900)	total: 1m 47s	remaining: 2m 54s
2000:	learn: 0.0265261	test: 0.0318070	best: 0.0318070 (2000)	total: 1m 52s	remaining: 2m 49s
2100:	learn: 0.0262489	test: 0.0317664	best: 0.0317655 (2088)	total: 1m 58s	remaining: 2m 43s
2200:	learn: 0.0259766	test: 0.0317106	best: 0.0317102 (2199)	total: 2m 4s	remaining: 2m 38s
2300:	learn: 0.0257214	test: 0.0316619	best: 0.0316619 (2300)	total: 2m 10s	remaining: 2m 33s
2400:	learn: 0.0254696	test: 0.0316288	best: 0.0316288 (2400)	total: 2m 16s	remaining: 2m 28s
2500:	learn: 0.0252365	test: 0.0316041	best: 0.0316041 (2500)	total: 2m 22s	remaining: 2m 22s
2600:	learn: 0.0250268	test: 0.0315763	best: 0.0315753 (2599)	total: 2m 28s	remaining: 2m 17s
2700:	learn: 0.0248367	test: 0.0315608	best: 0.0315601 (2694)	total: 2m 34s	remaining: 2m 11s
2800:	learn: 0.0246355	test: 0.0315362	best: 0.0315360 (2797)	total: 2m 40s	remaining: 2m 6s
2900:	learn: 0.0244253	test: 0.0315235	best: 0.0315233 (2896)	total: 2m 47s	remaining: 2m
3000:	learn: 0.0242404	test: 0.0314930	best: 0.0314930 (3000)	total: 2m 53s	remaining: 1m 55s
3100:	learn: 0.0240634	test: 0.0314743	best: 0.0314738 (3093)	total: 2m 59s	remaining: 1m 49s
3200:	learn: 0.0238650	test: 0.0314544	best: 0.0314544 (3200)	total: 3m 5s	remaining: 1m 44s
3300:	learn: 0.0236760	test: 0.0314340	best: 0.0314340 (3300)	total: 3m 11s	remaining: 1m 38s
3400:	learn: 0.0235010	test: 0.0314220	best: 0.0314220 (3400)	total: 3m 17s	remaining: 1m 32s
3500:	learn: 0.0233379	test: 0.0314116	best: 0.0314114 (3498)	total: 3m 23s	remaining: 1m 26s
3600:	learn: 0.0231729	test: 0.0313983	best: 0.0313973 (3571)	total: 3m 29s	remaining: 1m 21s
3700:	learn: 0.0230084	test: 0.0313845	best: 0.0313824 (3696)	total: 3m 34s	remaining: 1m 15s
3800:	learn: 0.0228412	test: 0.0313749	best: 0.0313739 (3793)	total: 3m 40s	remaining: 1m 9s
3900:	learn: 0.0226780	test: 0.0313623	best: 0.0313623 (3900)	total: 3m 46s	remaining: 1m 3s
4000:	learn: 0.0225237	test: 0.0313569	best: 0.0313555 (3982)	total: 3m 53s	remaining: 58.3s
4100:	learn: 0.0223663	test: 0.0313496	best: 0.0313494 (4091)	total: 3m 59s	remaining: 52.6s
4200:	learn: 0.0221976	test: 0.0313351	best: 0.0313347 (4194)	total: 4m 6s	remaining: 46.8s
4300:	learn: 0.0220390	test: 0.0313300	best: 0.0313293 (4297)	total: 4m 12s	remaining: 41.1s
4400:	learn: 0.0218846	test: 0.0313271	best: 0.0313265 (4398)	total: 4m 19s	remaining: 35.3s
4500:	learn: 0.0217276	test: 0.0313186	best: 0.0313181 (4492)	total: 4m 25s	remaining: 29.4s
4600:	learn: 0.0215784	test: 0.0313122	best: 0.0313122 (4600)	total: 4m 31s	remaining: 23.6s
4700:	learn: 0.0214377	test: 0.0313121	best: 0.0313106 (4689)	total: 4m 37s	remaining: 17.7s
4800:	learn: 0.0212850	test: 0.0313097	best: 0.0313092 (4791)	total: 4m 44s	remaining: 11.8s
4900:	learn: 0.0211575	test: 0.0313051	best: 0.0313039 (4877)	total: 4m 50s	remaining: 5.87s
4999:	learn: 0.0210134	test: 0.0313027	best: 0.0313018 (4945)	total: 4m 56s	remaining: 0us

bestTest = 0.03130175151
bestIteration = 4945

Shrink model to first 4946 iterations.
Fold RMSE: 0.031302
Fold R²  : 0.948899

Fold 5
0:	learn: 0.1402253	test: 0.1413712	best: 0.1413712 (0)	total: 57.5ms	remaining: 4m 47s
100:	learn: 0.0559374	test: 0.0562822	best: 0.0562822 (100)	total: 4.54s	remaining: 3m 40s
200:	learn: 0.0414195	test: 0.0418528	best: 0.0418528 (200)	total: 9.2s	remaining: 3m 39s
300:	learn: 0.0372538	test: 0.0378636	best: 0.0378636 (300)	total: 14.6s	remaining: 3m 48s
400:	learn: 0.0353755	test: 0.0361358	best: 0.0361358 (400)	total: 20.3s	remaining: 3m 52s
500:	learn: 0.0340353	test: 0.0350611	best: 0.0350611 (500)	total: 25.6s	remaining: 3m 49s

In [17]:
cat_cv_rmse = np.mean(cat_scores)

print("\nCatBoost Results")
print("-" * 30)
print("Fold Scores:", cat_scores)
print("Mean RMSE:", cat_cv_rmse)

CatBoost Results
------------------------------
Fold Scores: [np.float64(0.030865348834991323), np.float64(0.031170198227856438), np.float64(0.030477521893019267), np.float64(0.031301751378637756), np.float64(0.030483711586605337)]
Mean RMSE: 0.030859706384222023

In [18]:
joblib.dump(
    best_cat_model,
    "models/best_model3.pkl"
)

joblib.dump(
    best_cat_model,
    "models/best_catboost3.pkl"
)

['models/best_catboost3.pkl']

In [19]:
import joblib
import pandas as pd

# Load model
model = joblib.load("models/best_catboost3.pkl")

# Feature importance
feature_importance = pd.DataFrame({
    "feature": FEATURE_COLS,
    "importance": model.get_feature_importance()
})

feature_importance = (
    feature_importance
    .sort_values("importance", ascending=False)
    .reset_index(drop=True)
)

print(feature_importance)

                feature  importance
0              RoadType   30.590694
1               geohash   15.110093
2       roadtype_period   10.531422
3              geo_road    9.780796
4         NumberofLanes    5.005820
5              cos_hour    3.561590
6         LargeVehicles    3.059554
7            geo_period    3.012323
8   lat_lon_interaction    2.801335
9                   lon    2.592429
10             sin_hour    2.421346
11                 hour    1.606894
12              hour_sq    1.571948
13             geo_hour    1.384556
14                  day    1.286868
15                  lat    1.208766
16               period    1.164273
17             geo_temp    0.908853
18          geo_weather    0.652808
19         weather_temp    0.363307
20       temperature_sq    0.290716
21          Temperature    0.273448
22          temp_bucket    0.269323
23              Weather    0.238027
24            Landmarks    0.217417
25      is_morning_peak    0.054186
26      is_evening_peak    0.041209

In [20]:
from sklearn.metrics import r2_score

# Training features
X_train_full = train_df[FEATURE_COLS]
y_train_full = train_df["demand"]

# Predictions on training data
train_preds = best_cat_model.predict(X_train_full)

# R² score
train_r2 = r2_score(y_train_full, train_preds)

print(f"Training R² Score: {train_r2:.6f}")

Training R² Score: 0.967139

In [21]:
def prepare_test_data(
    test_df
):
    """
    Complete preprocessing pipeline
    for inference.
    """

    df = test_df.copy()

    # cleaning
    df = clean_dataset(df)

    # feature engineering
    df = engineer_features(df)

    return df

In [22]:
test_processed = prepare_test_data(
    test_df
)

/tmp/ipykernel_15764/3791486193.py:17: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  str_cols = df.select_dtypes(include=["object"]).columns

In [23]:
test_processed.head()

,Index,geohash,day,timestamp,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather,...,temperature_sq,hour_sq,is_morning_peak,is_evening_peak,lat_lon_interaction,temp_bucket,weather_temp,geo_weather,geo_road,geo_temp
0,0,qp02z1,49,2:15,residential,1,not allowed,no,16.457339,sunny,...,254.386654,4,0,0,-497.036,mild,sunny_mild,qp02z1_sunny,qp02z1_residential,qp02z1_mild
1,1,qp02z9,49,2:15,residential,1,not allowed,no,6.476213,snowy,...,35.465127,4,0,0,-497.036,cold,snowy_cold,qp02z9_snowy,qp02z9_residential,qp02z9_cold
2,2,qp02yf,49,2:15,residential,3,allowed,yes,22.318203,sunny,...,475.783964,4,0,0,-497.036,mild,sunny_mild,qp02yf_sunny,qp02yf_residential,qp02yf_mild
3,3,qp02z6,49,2:15,residential,2,not allowed,yes,16.457339,rainy,...,254.386654,4,0,0,-497.036,mild,rainy_mild,qp02z6_rainy,qp02z6_residential,qp02z6_mild
4,4,qp02zd,49,2:15,residential,1,not allowed,no,18.266162,foggy,...,315.386520,4,0,0,-497.036,mild,foggy_mild,qp02zd_foggy,qp02zd_residential,qp02zd_mild

In [24]:
X_test = test_processed[FEATURE_COLS]

test_preds = best_cat_model.predict(X_test)

In [25]:
import os
submission = pd.DataFrame({
    "Index": test_df["Index"],
    "demand": test_preds
})
os.makedirs(
    "../data/submissions",
    exist_ok=True
)

submission.to_csv(
    "../data/submissions/submission_4rthjune2.csv",
    index=False
)

print(submission.head())

   Index    demand
0      0  0.058944
1      1  0.020547
2      2  0.020058
3      3  0.026599
4      4  0.047562